# Generated by Django 2.2.7 on 2019-11-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
