# Generated by Django 2.2.7 on 2019-11-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_weight',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
