# Generated by Django 2.2.7 on 2019-11-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0002_auto_20191114_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_to_meal',
            field=models.BooleanField(default=False),
        ),
    ]
