# Generated by Django 2.2.7 on 2019-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0004_auto_20191128_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Energy (kcal/100g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbs',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Carbs (g per 100g )'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fats (g/100g of product)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Proteins (g per 100g of product)'),
        ),
    ]
