# Generated by Django 2.2.7 on 2019-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0005_auto_20191128_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fats (g/100g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Proteins (g per 100g)'),
        ),
    ]
