# Generated by Django 2.2.7 on 2019-11-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0006_auto_20191128_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calories',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Energy (kcal per 100g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fats (g per 100g)'),
        ),
    ]
