# Generated by Django 2.2.7 on 2019-11-29 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carb_count', '0009_auto_20191128_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fats',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Fat (g per 100g)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Protein (g per 100g)'),
        ),
    ]
